name: "🌱 Welcome - Join Always Green"
description: "Join Always Green"
title: "🌱 Join: <your-name>"
labels: ["welcome"]
body:
  - type: markdown
    attributes:
      value: |
        ## Welcome to Always Green! 🌱

        Submit this issue to join!

  - type: checkboxes
    id: acknowledgment
    attributes:
      label: "Join"
      options:
        - label: "Joined Always Green!"
          required: true
